- job:
   name: 'configure_auto_test'
   description: 'Auto configure Jenkins Job to perform automated tests'
   project-type: freestyle
   block-downstream: false
   auth-token: slave
   parameters:
      - node:
          name: List of connected nodes
          type: multi-select
          ignore-offline-nodes: true
          allowed-multiselect: false
      - choice:
          name: Device
          Description: "List of connected devices"
          choices:
            - Samsung
            - Oppo
            - HTC
      - extended-choice:
          name: Slaves
          description: "Available Nodes"
          type: 'PT_CHECKBOX' 
          value: nandu,nikhil,manikanta,ravichandra

   builders:
     - shell: python jenkins_file.py $Device $Slaves
   scm:
     - git:
          url: https://github.com/OSrivalli/jobs
          credentials:
            - name: srivalli
          branches:
            - '*/master'
          skip-tag: true

- project:
    name: Test_Automation
    jobs:
      - configure_auto_test

